### ISSUE TITLE
Messages in posts are hardly readable when selected.

### ISSUE THREAD

**Issue by Vaan99** [destinygg/rdestinycss#3]
Posts are hard to read when highlighted, album for example: https://imgur.com/a/WCgW3

**Comment by xiphirx** [comment]
This is because of an RES update. I'm currently away on vacation in Hawaii, so it might be a few days before I fix it. PRs welcome in the mean time.

**Comment by xiphirx** [comment]
6df4cb9d1dca558cf182f66d81c0af443fe1ce96
